digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;

letter = "A" | "B" | "C" | ... | "Z" | "a" | "b" | ... | "z" ;

integer = digit, { digit } ;

sign = "+" | "-" ;

number = [sign], integer ;

name = firstname , " ", lastname ;

first_name = letter, {letter} ;

last_name = letter, {letter} ;

account_number = letter, letter, digit, digit, digit, digit, digit, digit ;

deposit_command = "deposit", " ", account_number, " ", number ;

withdraw_command = "withdraw", " ", account_number, " ", number ;

balance_command = "balance", " ", account_number ;

create_command = "create", " ", first_name, " ", last_name, " ", account_number ;

command = deposit_command | withdraw_command | balance_command | create_command ;

program = command, { newline, command } ;

newline = "\n" ;
